[package]
name = "owlib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iref = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "*"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3"
harriet = "0.1"